apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
#apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbiservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hbiservices
    spec:
      # imagePullSecrets:
      #   - name: regcred
      containers:
      - name: hbiservices
        image: raj73docker/hbiservices:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000     
---
apiVersion: v1
kind: Service
metadata:
  name: hbiservices
spec:
  type: LoadBalancer
  selector:
    app: hbiservices
  ports:
  - name: hbiservices-port
    port: 8080
    targetPort: 8080
    protocol: TCP