---
# This Playbook runs all the common plays in the deployment

    #- name: Update the machine
    #  command: sudo apt-get clean && update -y

#- name: Installing AWS CLI
#  command: apt-get install awscli

#- name: Installing Python Pip
#  command: apt-get install python-pip python-dev build-essential -y

#- name: Install pip
#  apt: name=python-pip state=present

#- name: install docker-py
#  pip: name=docker-py>=1.7.0

#- name: Installing essentials
  #command: apt-get install curl apt-transport-https ca-certificates curl software-properties-common -y

#- name: Installing Docker-ce
#  command: apt-get install docker-ce=18.03.0~ce-0~ubuntu

#- name: Installing docker
#  command: apt install docker.io -y

#- name: Adding user to group
#  command: sudo usermod -aG docker ${USER}

#- name: Restarting docker service
#  command: service docker restart
